# application.yml

# 配置服务器信息
server:
  port: 8080

spring:
  # mysql 数据库相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/employees?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true

# springdoc-openapi 的各种配置
springdoc:
  swagger-ui:
    # 指定 Swagger UI 的访问路径
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    # 指定生成 API 文档的路径
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lizhengi.web

# Knife4j 的增强配置，不需要增强可以不配
knife4j:
  # 启用 Knife4j
  enable: true
  setting:
    language: zh_cn